CREATE TABLE TBL_TEST_RESULTS
(
       USER_NM VARCHAR(1000),
       TEST_DT VARCHAR(1000),
       BROWSER VARCHAR(1000),
       TEST_NM VARCHAR(1000),
       TEST_STEP VARCHAR(1000),
       EXPECTED_RESULT VARCHAR(1000),
       PASS VARCHAR(1) DEFAULT 'N',
       FAIL VARCHAR(1) DEFAULT 'N',
       COMMENTS VARCHAR(2500)
)
